"""empty message

Revision ID: 6492ba32e28b
Revises: a6f697255cfc
Create Date: 2024-01-01 20:48:25.230332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6492ba32e28b'
down_revision = 'a6f697255cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
